#ifdef _OPENMP
# include <omp.h>
#endif // ifdef _OPENMP

#include <string>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

// See this header file for discussion of numpy compilation issues.
#include "so3g_numpy.h"

// File generated by the build system
#include "_version.h"

// Include headers with registration functions
#include "exceptions.h"
#include "hkagg.h"
#include "so_linterp.h"
#include "Butterworth.h"
#include "Intervals.h"
#include "Ranges.h"
#include "Projection.h"
#include "fitting_ops.h"

// Declaration here, since there is no header file for array_ops.
void register_array_ops(py::module_ & m);

namespace py = pybind11;


const std::string version()
{
    return SO3G_VERSION_STRING;
}

py::object useful_info() {
    int omp_num_threads = 1;
#pragma omp parallel
    {
        #ifdef _OPENMP
        if (omp_get_thread_num() == 0)
            omp_num_threads = omp_get_num_threads();
        #endif
    }
    py::dict output;
    output["omp_num_threads"] = omp_num_threads;
    output["version"] = version();
    return output;
}


static void* _so3g_import_array() {
    import_array();
    return NULL;
}


PYBIND11_MODULE(libso3g, m) {
    _so3g_import_array();

    m.def("version", &version);
    m.def("useful_info", &useful_info);

    register_exceptions(m);
    register_hkagg(m);
    register_butterworth(m);
    register_so_linterp(m);
    register_intervals(m);
    register_ranges(m);
    register_array_ops(m);
    register_projection(m);
    register_fitting_ops(m);
}
