# Deploy tagged releases.

name:  Deploy Release

on:
  push:
    tags:
      - '*'

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

jobs:
  sdist:
    name: Python source dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: pip install twine
      - name: Create dist directory
        run: mkdir -p dist && rm -f dist/*
      - name: Build source package
        run: ./wheels/build_sdist.sh
      - name: Upload to PyPI
        run: |
          python -m twine upload dist/so3g*.tar.gz
  wheels-py37:
    name: Python 3.7 wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      CIBW_BUILD: cp37-macosx_x86_64 cp37-manylinux_x86_64
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
      CIBW_MANYLINUX_I686_IMAGE: manylinux2014
      CIBW_BUILD_VERBOSITY: 3
      CIBW_ENVIRONMENT_LINUX: "CC=gcc CXX=g++ CFLAGS='-O3 -fPIC' CXXFLAGS='-O3 -fPIC -std=c++11' BOOST_ROOT=/usr/local"
      CIBW_ENVIRONMENT_MACOS: "CC=clang CXX=clang++ CFLAGS='-O3 -fPIC' CXXFLAGS='-O3 -fPIC -std=c++11 -stdlib=libc++' BOOST_ROOT=/usr/local"
      CIBW_BEFORE_BUILD_LINUX: ./wheels/install_deps_linux.sh
      CIBW_BEFORE_BUILD_MACOS: ./wheels/install_deps_osx.sh
      CIBW_REPAIR_WHEEL_COMMAND_LINUX: ./wheels/repair_wheel_linux.sh {dest_dir} {wheel}
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: ./wheels/repair_wheel_macos.sh {dest_dir} {wheel} {delocate_archs}
      CIBW_BEFORE_TEST:
      CIBW_TEST_COMMAND: python -c 'import so3g.smurf.reader; from spt3g import core'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      - name: Install cibuildwheel
        run: |
          python -m pip install twine cibuildwheel==2.3.1
      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - name: Upload to PyPI
        run: |
          python -m twine upload wheelhouse/so3g*.whl
  wheels-py38:
    name: Python 3.8 wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      CIBW_BUILD: cp38-macosx_x86_64 cp38-manylinux_x86_64
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
      CIBW_MANYLINUX_I686_IMAGE: manylinux2014
      CIBW_BUILD_VERBOSITY: 3
      CIBW_ENVIRONMENT_LINUX: "CC=gcc CXX=g++ CFLAGS='-O3 -fPIC' CXXFLAGS='-O3 -fPIC -std=c++11' BOOST_ROOT=/usr/local"
      CIBW_ENVIRONMENT_MACOS: "CC=clang CXX=clang++ CFLAGS='-O3 -fPIC' CXXFLAGS='-O3 -fPIC -std=c++11 -stdlib=libc++' BOOST_ROOT=/usr/local"
      CIBW_BEFORE_BUILD_LINUX: ./wheels/install_deps_linux.sh
      CIBW_BEFORE_BUILD_MACOS: ./wheels/install_deps_osx.sh
      CIBW_REPAIR_WHEEL_COMMAND_LINUX: ./wheels/repair_wheel_linux.sh {dest_dir} {wheel}
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: ./wheels/repair_wheel_macos.sh {dest_dir} {wheel} {delocate_archs}
      CIBW_BEFORE_TEST:
      CIBW_TEST_COMMAND: python -c 'import so3g.smurf.reader; from spt3g import core'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      - name: Install cibuildwheel
        run: |
          python -m pip install twine cibuildwheel==2.3.1
      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - name: Upload to PyPI
        run: |
          python -m twine upload wheelhouse/so3g*.whl
  wheels-py39:
    name: Python 3.9 wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      CIBW_BUILD: cp39-macosx_x86_64 cp39-manylinux_x86_64
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
      CIBW_MANYLINUX_I686_IMAGE: manylinux2014
      CIBW_BUILD_VERBOSITY: 3
      CIBW_ENVIRONMENT_LINUX: "CC=gcc CXX=g++ CFLAGS='-O3 -fPIC' CXXFLAGS='-O3 -fPIC -std=c++11' BOOST_ROOT=/usr/local"
      CIBW_ENVIRONMENT_MACOS: "CC=clang CXX=clang++ CFLAGS='-O3 -fPIC' CXXFLAGS='-O3 -fPIC -std=c++11 -stdlib=libc++' BOOST_ROOT=/usr/local"
      CIBW_BEFORE_BUILD_LINUX: ./wheels/install_deps_linux.sh
      CIBW_BEFORE_BUILD_MACOS: ./wheels/install_deps_osx.sh
      CIBW_REPAIR_WHEEL_COMMAND_LINUX: ./wheels/repair_wheel_linux.sh {dest_dir} {wheel}
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: ./wheels/repair_wheel_macos.sh {dest_dir} {wheel} {delocate_archs}
      CIBW_BEFORE_TEST:
      CIBW_TEST_COMMAND: python -c 'import so3g.smurf.reader; from spt3g import core'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      - name: Install cibuildwheel
        run: |
          python -m pip install twine cibuildwheel==2.3.1
      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - name: Upload to PyPI
        run: |
          python -m twine upload wheelhouse/so3g*.whl
